server:
  port: 8080

spring:
  application:
    name: player-api

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/
