spring:
  application:
    name: eureka-service-registry
server:
  port: 8282

eureka:
   client:
     register-with-eureka: false
     fetch-registry: false
     serviceUrl:
       defaultZone: http://localhost:8282/eureka/