server:
  port: 8181

spring:
  application:
    name: game-api

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8282/eureka/
